app = "feedbuilderly"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

# Mount persistent volume for database
[mounts]
  source = "feedbuilder_data"
  destination = "/app/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
