name: Create Fly Volume

on:
  workflow_dispatch

jobs:
  create-volume:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [fra, ams]
    steps:
      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh

      - name: Add flyctl to PATH
        run: echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Create Volume in ${{ matrix.region }}
        run: |
          flyctl volumes create feedbuilder_data \
            --size 3 \
            --region ${{ matrix.region }} \
            --app feedbuilder \
            --yes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_AUTH_TOKEN }}

      - name: Verify Volume
        run: flyctl volumes list -a feedbuilder
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_AUTH_TOKEN }}
