name: Create Fly Volume

on:
  workflow_dispatch

jobs:
  create-volume:
    runs-on: ubuntu-latest
    steps:
      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh

      - name: Add flyctl to PATH
        run: echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Create Volume
        run: |
          flyctl volumes create feedbuilder_data \
            --size 3 \
            --region ams \
            --app feedbuilderly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_AUTH_TOKEN }}

      - name: Verify Volume
        run: flyctl volumes list
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_AUTH_TOKEN }}
